# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cereal, intervals, lens, linear, STL }:

cabal.mkDerivation (self: {
  pname = "level";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ cereal intervals lens linear STL ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
